// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsZKLiL9j8tSSugI8abpV2rnwY6MtdSMc',
    appId: '1:755013380692:web:b179bb993b867a37e7dbc1',
    messagingSenderId: '755013380692',
    projectId: 'tracking-app-a7c10',
    authDomain: 'tracking-app-a7c10.firebaseapp.com',
    storageBucket: 'tracking-app-a7c10.appspot.com',
    measurementId: 'G-40E5LQDBMK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjEYD4nRopbz-6H48PaMdqbthaFw5_XN0',
    appId: '1:755013380692:android:78dd76e4bc9631cce7dbc1',
    messagingSenderId: '755013380692',
    projectId: 'tracking-app-a7c10',
    storageBucket: 'tracking-app-a7c10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWVwkbo7CVdQZEUFopOk3x-BD2ntgHYWY',
    appId: '1:755013380692:ios:a8e56f4dcfe0916de7dbc1',
    messagingSenderId: '755013380692',
    projectId: 'tracking-app-a7c10',
    storageBucket: 'tracking-app-a7c10.appspot.com',
    iosBundleId: 'com.example.trackingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWVwkbo7CVdQZEUFopOk3x-BD2ntgHYWY',
    appId: '1:755013380692:ios:cc9aa3b3a4fa9affe7dbc1',
    messagingSenderId: '755013380692',
    projectId: 'tracking-app-a7c10',
    storageBucket: 'tracking-app-a7c10.appspot.com',
    iosBundleId: 'com.example.trackingapp.RunnerTests',
  );
}
